import Box from '@mui/material/Box'
import Stack from '@mui/material/Stack'
import Typography from '@mui/material/Typography'
import Head from 'next/head'
import { withUser, AuthAction, withUserTokenSSR } from 'next-firebase-auth'
import { UserAvatar } from '../src/Components/UserAvatar'

function Home() {
  return (
    <>
      <Head>
        <title>Our Shopping List</title>
        <meta
          name='a shopping list for busy couples that constatly forget theirs at home'
          content='Generated by create next app'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        sx={{
          pt: 4,
          px: 1,
          display: 'flex',
          justifyContent: 'center'
        }}
      >
        <UserAvatar></UserAvatar>
        <Stack direction='column'>
          <Typography variant='h2' textAlign='center'>
            Our Shopping List
          </Typography>
        </Stack>
      </Box>
    </>
  )
}

export const getServerSideProps = withUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
})()

export default withUser({
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN
})(Home)
